site_name: XCPC IO
site_url: https://xcpcio.com
site_description: |
  Info Site of XCPC

repo_name: XCPCIO
repo_url: https://github.com/XCPCIO/XCPCIO
edit_uri: tree/master/docs

copyright: |
  Copyright &copy; 2020 - 2022 <a href="https://github.com/XCPCIO/XCPCIO"  target="_blank" rel="noopener">XCPC IO</a>
  #beian

docs_dir: docs

theme:
  name: material
  custom_dir: theme

  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: true

  language: en

  features:
    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dracula
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/github
    logo: material/airplane
  favicon: assets/favicon.png

markdown_extensions:
  - admonition:
  - abbr:
  - attr_list:
  - def_list:
  - footnotes:
  - md_in_html:
  - meta:
  - markdown.extensions.smarty:
      smart_quotes: false
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ""
      toc_depth: 2-3
  - pymdownx.arithmatex:
  - pymdownx.betterem:
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.keys:
  - pymdownx.tilde:
  - pymdownx.mark:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      normalize_issue_symbols: true
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.progressbar:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      check_paths: true
      base_path:
  - pymdownx.saneheaders:

extra:
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/XCPCIO/XCPCIO
  var:
    mirror_download_host: !ENV [MIRROR_DOWNLOAD_HOST, "./"]
    upload_file_host: !ENV [UPLOAD_FILE_HOST, "./"]

plugins:
  - search:
      lang: ja
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - minify:
      minify_html: true
  - mkdocs-material-extras:
      enable_mathjax: !ENV [ENABLE_MATHJAX, true]
  - macros:
  - redirects:
      redirect_maps:
        "index.md": "info/calendar.md"

nav:
  - INFORMATION:
      - News: info/news.md
      - Calendar: info/calendar.md
      - ICPC:
          - Getting Started: info/icpc/index.md
          - "47th":
              - Getting Started: info/icpc/47th/index.md
              - 网络预选赛: info/icpc/47th/online.md
              - 沈阳: info/icpc/47th/shenyang.md
              - 西安: info/icpc/47th/xian.md
              - 合肥: info/icpc/47th/hefei.md
              - 济南: info/icpc/47th/jinan.md
              - 杭州: info/icpc/47th/hangzhou.md
              - 南京: info/icpc/47th/nanjing.md
              - 香港: info/icpc/47th/hongkong.md
              - EC Final: info/icpc/47th/ec.md
          - "46th":
              - Getting Started: info/icpc/46th/index.md
              - 网络预选赛: info/icpc/46th/online.md
              - 济南站: info/icpc/46th/jinan.md
              - 沈阳站: info/icpc/46th/shenyang.md
              - 上海站: info/icpc/46th/shanghai.md
              - 南京站: info/icpc/46th/nanjing.md
              - 澳门站: info/icpc/46th/macau.md
              - 昆明站: info/icpc/46th/kunming.md
              - EC Final: info/icpc/46th/ec.md
          - "2020":
              - Getting Started: info/icpc/2020/index.md
              - 牛客-小米: info/icpc/2020/nowcoder-xiaomi.md
              - 上海: info/icpc/2020/shanghai.md
              - 南京: info/icpc/2020/nanjing.md
              - 济南: info/icpc/2020/jinan.md
              - 昆明: info/icpc/2020/kunming.md
              - 银川: info/icpc/2020/yinchuan.md
              - 沈阳: info/icpc/2020/shenyang.md
              - 澳门: info/icpc/2020/macau.md
              - EC Final: info/icpc/2020/ec.md
              - World Finals: info/icpc/2020/world-finals.md
          - "2019":
              - World Finals: info/icpc/2019/world-finals.md
              - Hong Kong: info/icpc/2019/hongkong.md
              - EC Final: info/icpc/2019/ec-final.md
          - "2018":
              - 青岛: info/icpc/2018/tingdao.md
              - World Finals: info/icpc/2018/world-finals.md
          - "2017":
              - World Finals: info/icpc/2017/world-finals.md
          - "2015":
              - 北京: info/icpc/2015/beijing.md
              - 亚洲区决赛: info/icpc/2015/ecfinal.md
      - CCPC:
          - Getting Started: info/ccpc/index.md
          - "8th":
              - Getting Started: info/ccpc/8th/index.md
              - 网络选拔赛: info/ccpc/8th/preliminary-contest.md
              - 女生赛: info/ccpc/8th/girl.md
              - 高职专场: info/ccpc/8th/gaozhi.md
              - 桂林站: info/ccpc/8th/guilin.md
              - 威海站: info/ccpc/8th/weihai.md
              - 绵阳站: info/ccpc/8th/mianyang.md
              - 广州站: info/ccpc/8th/guangzhou.md
          - "7th":
              - Getting Started: info/ccpc/7th/index.md
              - 网络选拔赛: info/ccpc/7th/preliminary-contest.md
              - 女生赛: info/ccpc/7th/girl.md
              - 桂林站: info/ccpc/7th/guilin.md
              - 广州站: info/ccpc/7th/guangzhou.md
              - 威海站: info/ccpc/7th/weihai.md
              - 哈尔滨站: info/ccpc/7th/harbin.md
          - "6th":
              - Getting Started: info/ccpc/6th/index.md
              - 网络选拔赛: info/ccpc/6th/preliminary-contest.md
              - 女生赛: info/ccpc/6th/wfinal.md
              - 秦皇岛: info/ccpc/6th/qinhuangdao.md
              - 威海: info/ccpc/6th/weihai.md
              - 绵阳: info/ccpc/6th/mianyang.md
              - 长春: info/ccpc/6th/changchun.md
              - 总决赛: info/ccpc/6th/final.md
          - "5th":
              - 哈尔滨: info/ccpc/5th/harbin.md
              - 总决赛: info/ccpc/5th/final.md
      - Provincial Contest:
          - "2023":
              - 四川省赛: info/provincial-contest/2023/sichuan/sccpc.md
          - "2022":
              - 浙江省赛: info/provincial-contest/2022/zjcpc.md
              - 湖北省赛: info/provincial-contest/2022/hbcpc.md
          - "2021":
              - 浙江省赛: info/provincial-contest/2021/zjcpc.md
              - 江西省赛: info/provincial-contest/2021/jiangxi.md
          - "2020":
              - 浙江省赛: info/provincial-contest/2020/zjcpc.md
              - 江西省赛: info/provincial-contest/2020/jiangxicpc.md
              - 河南省赛: info/provincial-contest/2020/henancpc.md
              - 江苏省赛: info/provincial-contest/2020/jiangsucpc.md
          - "2019":
              - 浙江省赛: info/provincial-contest/2019/zjcpc.md
              - 山东省赛: info/provincial-contest/2019/sdcpc.md
              - 陕西省赛: info/provincial-contest/2019/sxcpc.md
              - 江西省赛: info/provincial-contest/2019/jscpc.md
          - "2018":
              - 浙江省赛: info/provincial-contest/2018/zjcpc.md
          - "2017":
              - 浙江省赛: info/provincial-contest/2017/zjcpc.md
  - BOARD:
      - Getting Started: board/index.md
      - 数据格式: board/data-format.md
  - RATING:
      - Getting Started: rating/index.md
  - CODE LIBRARY:
      - Getting Started: code-library/index.md
      - 模版库列表: code-library/code-library-list.md
      - 模版库构建: code-library/code-library-build.md
  - SOFTWARE:
      - Getting Started: software/index.md
      - 浏览器:
          - Google Chrome: software/browser/google-chrome.md
          - Mozilla Firefox: software/browser/mozilla-firefox.md
      - 编译器:
          - Python: software/compiler/python.md
          - JDK8: software/compiler/jdk8.md
          - GCC: software/compiler/gcc.md
      - 编辑器:
          - VS Code: software/editor/vscode.md
      - 集成开发环境:
          - Dev Cpp: software/ide/dev-cpp.md
          - PyCharm: software/ide/pycharm.md
          - IntelliJ IDEA: software/ide/intellij-idea.md
          - Eclipse: software/ide/eclipse.md
          - Code::Blocks: software/ide/codeblocks.md
      - 其它:
          - Win RAR: software/other/winrar.md
          - SumatraPDF: software/other/sumatrapdf.md
      - OMS监考客户端: software/oms.md
      - CCPC竞赛软件包: software/ccpc-pack.md
  - ABOUT:
      - 关于本项目: about/index.md
      - 如何参与: about/htc.md
      - 格式手册: about/format.md
      - F.A.Q.: about/faq.md
