site_name: XCPC IO
site_url: https://xcpcio.com
repo_url: https://github.com/XCPCIO/XCPCIO
edit_uri: tree/master/docs/src/markdown
site_description: Info Site of XCPC
copyright: |
  Copyright &copy; 2020 <a href="https://github.com/XCPCIO/XCPCIO"  target="_blank" rel="noopener">XCPC IO</a>
  #beian

docs_dir: docs/src/markdown
theme:
  name: material
  custom_dir: docs/theme
  language: zh
  icon:
    repo: fontawesome/brands/github
    logo: material/library
  favicon: assets/favicon.png
  palette:
    scheme: dracula
    primary: deep purple
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs

nav:
  - INFORMATION:
    - Getting Started: index.md
    - ICPC:
      - Getting Started: info/icpc/index.md
      - '2020':
        - Getting Started: info/icpc/2020/index.md
        - 牛客-小米: info/icpc/2020/nowcoder-xiaomi.md
        - 上海: info/icpc/2020/shanghai.md 
        - 南京: info/icpc/2020/nanjing.md
        - 济南: info/icpc/2020/jinan.md
        - 银川: info/icpc/2020/yinchuan.md
      - '2019':
        - World Finals: info/icpc/2019/world-finals.md
        - Hong Kong: info/icpc/2019/hongkong.md
        - EC Final: info/icpc/2019/ec-final.md
      - '2018':
        - 青岛: info/icpc/2018/tingdao.md
        - World Finals: info/icpc/2018/world-finals.md
      - '2017':
        - World Finals: info/icpc/2017/world-finals.md
      - '2015':
        - 北京: info/icpc/2015/beijing.md
        - 亚洲区决赛: info/icpc/2015/ecfinal.md
    - CCPC:
      - Getting Started: info/ccpc/index.md
      - '2020':
        - Getting Started: info/ccpc/2020/index.md
        - 网络选拔赛: info/ccpc/2020/preliminary-contest.md
        - 女生赛: info/ccpc/2020/wfinal.md
        - 秦皇岛: info/ccpc/2020/qinhuangdao.md
        - 威海: info/ccpc/2020/weihai.md
        - 绵阳: info/ccpc/2020/mianyang.md
        - 长春: info/ccpc/2020/changchun.md
      - '2019':
        - 哈尔滨: info/ccpc/2019/harbin.md
        - 总决赛: info/ccpc/2019/final.md
    - 地区赛:
      - '2020':
        - 浙江省赛: info/provincial-contest/2020/zjcpc.md
        - 江西省赛: info/provincial-contest/2020/jiangxicpc.md
        - 河南省赛: info/provincial-contest/2020/henancpc.md
        - 江苏省赛: info/provincial-contest/2020/jiangsucpc.md
      - '2019':
        - 浙江省赛: info/provincial-contest/2019/zjcpc.md
        - 山东省赛: info/provincial-contest/2019/sdcpc.md
        - 陕西省赛: info/provincial-contest/2019/sxcpc.md
        - 江西省赛: info/provincial-contest/2019/jscpc.md
      - '2018':
        - 浙江省赛: info/provincial-contest/2018/zjcpc.md
      - '2017':
        - 浙江省赛: info/provincial-contest/2017/zjcpc.md
  - SOFTWARE:
    - Getting Started: software/index.md
    - 浏览器: 
      - Google Chrome: software/browser/google-chrome.md
      - Mozilla Firefox: software/browser/mozilla-firefox.md
    - 编译器:
      - Python: software/compiler/python.md
      - JDK8: software/compiler/jdk8.md
    - 编辑器:
      - VS Code: software/editor/vscode.md
    - 集成开发环境:
      - Dev Cpp: software/ide/dev-cpp.md 
      - PyCharm: software/ide/pycharm.md
      - IntelliJ IDEA: software/ide/intellij-idea.md
      - Eclipse: software/ide/eclipse.md
    - 其它:
      - Win RAR: software/other/winrar.md
      - SumatraPDF: software/other/sumatrapdf.md
    - OMS监考客户端: software/oms.md
    - CCPC竞赛软件包: software/ccpc-pack.md
  - CODE LIBRARY:
    - Getting Started: code-library/index.md
    - 模版库列表: code-library/code-library-list.md
    - 模版库构建: code-library/code-library-build.md
  - ABOUT: 
    - 关于本项目: about/index.md
    - 如何参与: about/htc.md
    - 格式手册: about/format.md
    - F.A.Q.: about/faq.md
    
markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ""
      toc_depth: 2-6
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - markdown.extensions.meta:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.saneheaders:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/XCPCIO/XCPCIO
  var:
    mirror_download_host: ./
    upload_file_host: ./
    assets_host: /assets/

extra_css:
  - assets/pymdownx-extras/extra.css
extra_javascript:
  - assets/pymdownx-extras/extra-uml.js

plugins:
  - search:
  - git-revision-date-localized
  - minify:
      minify_html: true
  - macros
